version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: tobeit-uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 4001:3001
    restart: always
    depends_on:
      - postgres
      - pgbouncer

  postgres:
    container_name: tobeit-postgres
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./pg-db:/var/lib/postgresql/data

  pgbouncer:
    container_name: tobeit-pgbouncer
    image: edoburu/pgbouncer
    restart: always
    env_file:
      - .env
    environment:
      - DB_USER=${POSTGRES_USERNAME}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
      - DB_NAME=${POSTGRES_DB_NAME}
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,${POSTGRES_USERNAME}
    ports:
      - 6432:6432
    volumes:
      - ./pb-bouncer:/etc/pgbouncer
    depends_on:
      - postgres
