mutation InsertUser(
  $email: String!
  $firstname: String!
  $lastname: String!
  $grade: String!
  $province: String!
  $phoneNum: String!
) {
  insert_user(
    userInput: {
      email: $email
      firstname: $firstname
      lastname: $lastname
      grade: $grade
      province: $province
      phoneNum: $phoneNum
    }
  ) {
    email
    firstname
    lastname
  }
}
