name: pnpm build
on:
  push :
    branches:
    - production
    - dev
  pull_request:
    branches:
    - production
    - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Generate Schema
      run: pnpm run db:generate
    - name: Build the project
      run: pnpm build
